# Generated by Django 5.2.7 on 2025-12-01 12:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concessionnaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concessionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=64)),
                ('siret', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='Le SIRET doit contenir exactement 14 chiffres', regex='^\\d{14}$')])),
            ],
            options={
                'verbose_name': 'Concessionnaire',
                'verbose_name_plural': 'Concessionnaires',
                'ordering': ['nom'],
            },
        ),
        migrations.RemoveField(
            model_name='location',
            name='client',
        ),
        migrations.RemoveField(
            model_name='location',
            name='voiture',
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('moto', 'Moto'), ('auto', 'Auto')], max_length=4)),
                ('marque', models.CharField(max_length=64)),
                ('chevaux', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('prix_ht', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('concessionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicules', to='concessionnaire.concessionnaire')),
            ],
            options={
                'verbose_name': 'Véhicule',
                'verbose_name_plural': 'Véhicules',
                'ordering': ['marque', 'type'],
            },
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Voiture',
        ),
    ]
